### ISSUE TITLE
Missing MassMigrations in DemographyDebugger with certain values of T

### ISSUE THREAD

**Issue by jshleap** [jeromekelleher/msprime#37] opened 2016-08-30 14:15 UTC
I was trying to simulate the out of Africa model with updated parameters, I saw that not all the demography events were outputted by DemographyDebugger. As minimal example, try changing the T_EU_AS from your "21.2e3 / generation_time" for "23e3 / generation_time". Interestingly enough, if instead of those values you set T_EU_AS to "42e3 / generation_time" (the rest of values unchanged) It works again.

**Comment by jeromekelleher** [comment] 2016-08-31 09:58
Thanks very much for the bug report @jshleap. This is a bug in the debugger code caused by a problem with inexact matching for time values, when calculating the same value two different ways. There's an initial fix in #38. This does not affect the actual simulations, just the output of the debugger is incorrect.

If this is important to you, I can roll a new release of msprime with this fix and update pretty quickly. Otherwise, I'll merge this fix into master, but it might take some time before it's released, as there are some fairly big changes under way at the moment which I don't want to release before they're ready.

**Comment by jshleap** [comment] 2016-08-31 22:48
Hi @jeromekelleher , not problem at all. Since it does not affect the simulation, I will wait until you merge the fix to the master.

Best

**Comment by jeromekelleher** [comment] 2016-09-01 07:53
Great, thanks @jshleap. It'll be a few weeks before the updates will be released, so feel free to change your mind if you need the debug output sooner!

**Comment by jeromekelleher** [comment] 2016-10-06 10:49
Closed in #45.

**Closed** 2016-10-06 10:50 UTC
Labels: bug
